redis:
  image: redis
  volumes:
    - postgresdata:/var/lib/postgresql/data
db:
  image: postgres
web:
  build: .
  command: bundle exec puma -p 3000
  environment:
    REDIS_URL: "redis://redis:6379"
    DATABASE_URL: "postgres://postgres@db:5432/noferries"
  volumes:
    - .:/ferry-app
  ports:
    - "3000:3000"
  links:
    - db
    - redis
